var text1 = document.getElementById("text1");
var text2 = document.getElementById("text2");
var diffLine = document.getElementById("diff-line");
var diffWord = document.getElementById("diff-word");
var diffChar = document.getElementById("diff-char");
var output = document.getElementById("output");
var heading = document.querySelector('.container h1');
var infoLine = document.querySelector('.container p');
var resultsHeading = document.createElement('h2');

resultsHeading.textContent = 'Results';
resultsHeading.style.display = 'none';
var container = document.querySelector('.container');
container.insertBefore(resultsHeading, container.firstChild);


function countWords(text) {
  var words = text.split(/\s+/);
  return words.filter(function(word) {
    return word.length > 0;
  }).length;
}

diffLine.addEventListener("click", function() {
  rearrangeLayout();
  var text1Value = text1.value;
  var text2Value = text2.value;
  var changes = Diff.diffLines(text1Value, text2Value);
  var diffOutput = Diff.convertChangesToXML(changes);
  var lineCount = text1Value.split(/\r\n|\r|\n/).length;

  output.innerHTML = `<b>Total Lines </b>: ${lineCount}<br><br>${diffOutput}`;
});

diffWord.addEventListener("click", function() {
  rearrangeLayout();
  var text1Value = text1.value;
  var text2Value = text2.value;
  var changes = Diff.diffWords(text1Value, text2Value);
  var diffOutput = Diff.convertChangesToXML(changes);
  var countWordsResult = countWords(text1Value);

  output.innerHTML = `<b>Total Words </b>: ${countWordsResult}<br><br>${diffOutput}`;
});

diffChar.addEventListener("click", function() {
  rearrangeLayout();
  var text1Value = text1.value;
  var text2Value = text2.value;
  var changes = Diff.diffChars(text1Value, text2Value);
  var diffOutput = Diff.convertChangesToXML(changes);
  var charCount = text1Value.length;

  output.innerHTML = `<b>Total Characters </b>: ${charCount}<br><br>${diffOutput}`;
});

document.getElementById('reset-btn').addEventListener('click', function() {
  document.getElementById('text1').value = '';
  document.getElementById('text2').value = '';
  document.getElementById('output').innerHTML = '';
  resetLayout();
});

function resetLayout() {
  output.style.display = 'none';
  text1.style.width = '100%';
  text1.style.height = '20rem';
  text1.style.marginRight = '0';
  text2.style.width = '100%';
  text2.style.height = '20rem';
  text2.style.marginLeft = '0';
  infoLine.style.display = 'none';
  heading.style.display = 'block';
  resultsHeading.style.display = 'none';
  document.getElementById('text-selector').style.display = 'block';
  document.querySelector('.text-container label').style.display = 'block';
}

function rearrangeLayout() {
  resultsHeading.style.display = 'block';
  output.style.display = 'block';
  heading.style.display = 'none';
  infoLine.style.display = 'none';
  text1.style.width = 'calc(100%)';
  text1.style.height = '14rem';
  //text1.style.marginRight = '2rem';
  text2.style.width = 'calc(100%)';
  text2.style.height = '14rem';
  //text2.style.marginLeft = '2rem';
  document.getElementById('text-selector').style.display = 'none';
  document.querySelector('.text-container label').style.display = 'none';
}

function applySimpleFont() {
  text1.style.fontWeight = 'normal';
  text2.style.fontWeight = 'normal';
}

function applyBoldFont() {
  text1.style.fontWeight = 'bold';
  text2.style.fontWeight = 'bold';
}

text1.addEventListener('focus', function() {
  applyBoldFont();
});

text2.addEventListener('focus', function() {
  applyBoldFont();
});

text1.addEventListener('blur', function() {
  applySimpleFont();
});

text2.addEventListener('blur', function() {
  applySimpleFont();
});

var providedTexts = {
  'Lorem': 'Lorem ipsum dolor sit amet',
  '2': "'Ratan was not anxious to give up the freedom he found in America, but he did want to get out of the cold, which he never did get used to, complaining that he couldn't ever feel warm enough. Vowing that he would never live in a cold climate again, he left Ithaca as soon as his coursework was completed, but instead of returning to India, he headed out to Los Angeles, where he moved to an apartment complex, complete with swimming pool. He intended to use his architecture degree to get a job in the area and, eventually, to set up as an American architect. He had no intention of returning to India. However, his grandmother, Lady Navajbai, fell critically ill and called for him. He could not resist flying back to India to be with her. He had an American girlfriend at that time who was to follow him to India but never did. Lady Navajbai survived the crisis, but her health continued to deteriorate, and Ratan found himself extending his stay in India. In later life, Ratan spoke of having four serious girlfriends in his life and once even got engaged, but broke it off before the cards could be printed. But he never married, and the absence of a spouse and children has, over the years, caused some to speculate about what motivates this incredibly motivated man. The bond he felt with Lady Navajbai was strong enough to pull him out of Los Angeles and back to India, and after a short period of time, he got drawn into working in the Tata organization. It was one of those emotionally driven decisions. As for avoiding marriage, it could well be that the example of his parents' unhappy union made him gun-shy. What had moved Ratan to leave America and return to India to begin a career in the Tata organization? It was certainly not what he had traine.'",
  '3': 'Money stashed abroad is not always the money, which has been evaded from payment of taxes. Drug lords, terrorists groups, gangsters all over the world, along with International Syndicates also keep their money in safe havens, where they can lay their hands on it in times of need for their operational purposes. There is no mechanism with the Government to determine and say with cent per cent surety that the money hoarded abroad is only the one that has been evaded from payment of taxes and not the other crime linked cash. The Revenue Department and other agencies of the Government like the RAW and State Trading Organisations have their offices abroad. There is no common mandate to them to report any suspicious transactions by the Indians either visiting or staying abroad.The stark truth is that the black money is result of high level corruption prevailing in our country. The schemes meant for the poor, even as per the Government reports, are not implemented and the money siphoned off. Even laws permit every criminal whether in jail or on bail to hide their names and crimes and create false alibis. But, here the Government is creating alibis for those people whose names have been received and disclosed as the persons who are having cash, which is got illegally and is not from any known legal sources. They had stashed this cash in safe tax havens abroad. Even the Supreme Court, the Apex Court of India, says that nothing moves without bribery in India. A good and alert cop even on a tourist visa can spot Indians roaming about and visiting these safe tax havens or Swiss banks. The rest of the job of tracing the flight of black money from India can be done locally provided the Government has the will. So far, the Government has been.',
  '4': 'Money stashed abroad is not always the money, which has been evaded from payment of taxes. Drug lords, terrorists groups, gangsters all over the world, along with International Syndicates also keep their money in safe havens, where they can lay their hands on it in times of need for their operational purposes. There is no mechanism with the Government to determine and say with cent per cent surety that the money hoarded abroad is only the one that has been evaded from payment of taxes and not the other crime linked cash. The Revenue Department and other agencies of the Government like the RAW and State Trading Organisations have their offices abroad. There is no common mandate to them to report any suspicious transactions by the Indians either visiting or staying abroad. The stark truth is that the black money is result of high level corruption prevailing in our country. The schemes meant for the poor, even as per the Government reports, are not implemented and the money siphoned off. Even laws permit every criminal whether in jail or on bail to hide their names and crimes and create false alibis. But, here the Government is creating alibis for those people whose names have been received and disclosed as the persons who are having cash, which is got illegally and is not from any known legal sources. They had stashed this cash in safe tax havens abroad. Even the Supreme Court, the Apex Court of India, says that nothing moves without bribery in India. A good and alert cop even on a tourist visa can spot Indians roaming about and visiting these safe tax havens or Swiss banks. The rest of the job of tracing the flight of black money from India can be done locally provided the Government has the will. So far, the Government has been making . ',
  '5': 'Money stashed abroad is not always the money, which has been evaded from payment of taxes. Drug lords, terrorists groups, gangsters all over the world, along with International Syndicates also keep their money in safe havens, where they can lay their hands on it in times of need for their operational purposes. There is no mechanism with the Government to determine and say with cent per cent surety that the money hoarded abroad is only the one that has been evaded from payment of taxes and not the other crime linked cash. The Revenue Department and other agencies of the Government like the RAW and State Trading Organisations have their offices abroad. There is no common mandate to them to report any suspicious transactions by the Indians either visiting or staying abroad. The stark truth is that the black money is result of high level corruption prevailing in our country. The schemes meant for the poor, even as per the Government reports, are not implemented and the money siphoned off. Even laws permit every criminal whether in jail or on bail to hide their names and crimes and create false alibis. But, here the Government is creating alibis for those people whose names have been received and disclosed as the persons who are having cash, which is got illegally and is not from any known legal sources. They had stashed this cash in safe tax havens abroad. Even the Supreme Court, the Apex Court of India, says that nothing moves without bribery in India.A good and alert cop even on a tourist visa can spot Indians roaming about and visiting these safe tax havens or Swiss banks. The rest of the job of tracing the flight of black money from India can be done locally provided the Government has the will. So far, the Government has been making. ',
  '6': 'Scientific social work today has emerged as a problem solving profession. Compared to other disciplines, professional social work is relatively young. This profession helps individuals, groups and communities to find solutions for their problems. Finding solutions to problems enhances the quality of life and fosters development. Problems at any level (individual or social) can affect the interactions and relationships of individuals. Thus, the social adjustment and functioning get affected. Hence, social work intervention in solving problems promotes social functioning of individuals. Social work, over years has evolved a scientific knowledge base, clear skill sets and a strong value system, unique to the profession. Field level experience and research in addressing the problems of various client groups have resulted in developing different strategies and methods. These methods differ in their application of knowledge, skills, and techniques. The methods of social work are social case work, social group work, community organization, social action, social welfare administration, and social work research. They are broadly classified as primary and secondary methods. Case work, group work, and community organization which require direct interaction with the client are called the primary or direct methods. The other three, for which face to face contact with the client is not essential, are termed as secondary or indirect methods. In this unit, let us discuss the primary methods in detail. All human beings are part of society and everyone has different social roles and duties. While performing his/her duties and roles, individual faces many problems in one form or the other. Every individual reacts differently to his/her social, physical. ',
  '7': 'Thar Desert is situated on the border of India and Pakistan. A large part of it is in Marwar region of Rajasthan state. This place receives very little rain and there are no large rivers flowing. As a result very few trees grow here and very few crops can be grown. Only grass grows here. People here mainly depend upon grazing sheep, goats and camels. They take great care to store rain water for drinking for the animals and human beings and also for some agriculture. The shepherds usually travel across many states with their herds and usually come back before the rainy season to Thar. They make a living by selling goats and wool of the sheep. Many traders coming from Iran and Afghanistan or going to those countries pass through this desert. They stop over at convenient places to rest. Slowly these places grew into important towns and cities like Jaisalmer, Bikaner, Jodhpur. Many pilgrims going to Dwarka in Gujarat or to Mecca and Madina in Arabia or to Ajmer and Pushkar lake would pass through this area along with the traders. Thus over centuries people of many religions like Bohra Muslims, Sunni Muslims, Shia Muslims, Jains, Shaivas, Vaishnavas and Sikhs settled down in these towns and cities. Similarly, many Marwari traders from these parts went all over India and settled in several places. Some fifty years ago a large canal was built from the Punjab rivers to bring water to the Northern part of Thar desert. Along the canals came up new and prosperous villages many people from Punjab and Haryana came and settled down in these new villages. Earlier people mainly ate rotis made of bajra with green gram or black gram and ate of vegetables that grew on some trees (Sangri) and thorny bushes. These were dried and eaten throughout the year. ',
  '8': 'There is nothing either good or bad, but thinking makes it so. William Shakespeare, the magnificent observer of human behaviour and nature, discovered the key to destiny of mankind as well as this world, and artistically presented it for the coming generation in his specific creation Hamlet. If we think and observe even our own activities and their results - good and bad, successful and unsuccessful, well and woe till now, we will discover that everything happened and are happening on the basis of our decision and perception. Our thinking process has two opposites: one that ushers in healthy and favourable outputs is known as positive or good which always keeps us active and encourages us stoutly and confidently undertake one after another action or adventure, while the other results in unhealthy and vulnerable outputs that jeopardise our lives is known as bad or negative.Our positive thoughts and decisions, the output of our thinking, always lead us to growth and improvement while the negative lead us to perils and dangers. This power makes us decide the good and bad based on the human values we own. Our conscience, awareness, knowledge, experience, love, hatred, and other qualities influence us greatly in course of deciding the status of anything. It is natural or God gifted. Only human beings avail this opportunity out of the six senses that God has given all living beings in this planet. We have won the dominant position on this planet by the command of our thinking that has helped us develop our science and technology over time. Shakespeare was once asked to elaborate the above extract. He replied intelligently, A man cheerfully observed a religious fast seven days a week. His neighbour starved to death on the same diet.',
  '9': '"Scientific social work today has emerged as a problem solving profession. Compared to other disciplines, professional social work is relatively young. This profession helps individuals, groups and communities to find solutions for their problems. Finding solutions to problems enhances the quality of life and fosters development. Problems at any level (individual or social) can affect the interactions and relationships of individuals. Thus, the social adjustment and functioning get affected. Hence, social work intervention in solving problems promotes social functioning of individuals. Social work, over years has evolved a scientific knowledge base, clear skill sets and a strong value system, unique to the profession. Field level experience and research in addressing the problems of various client groups have resulted in developing different strategies and methods. These methods differ in their application of knowledge, skills, and techniques. The methods of social work are social case work, social group work, community organization, social action, social welfare administration, and social work research. They are broadly classified as primary and secondary methods. Case work, group work, and community organization which require direct interaction with the client are called the primary or direct methods. The other three, for which face to face contact with the client is not essential, are termed as secondary or indirect methods. In this unit, let us discuss the primary methods in detail. All human beings are part of society and everyone has different social roles and duties. While performing his/her duties and roles, individual faces many problems in one form or the other. Every individual reacts differently to his/her social, physical. "',
  '10': "A democratic country needs effective leadership to lead its citizens to new heights and horizons. Effective leadership helps our nation during times of difficulties. It makes a business organization successful. It enables a nongovernmental organization to fulfil its mission. It fulfils the goal of social work. The effective leadership and guidance from parents enable children to develop their personality. The absence of leadership affects the functioning of any organisation. Without proper leadership, organizations move slowly, stagnate, and lose their way. The absence or failure of leadership may lead to ineffective decision making. A social worker can't perform effectively without leadership skills. Leadership is a process whereby an individual influences a group of individuals to achieve a common goal. It is a process by which a person influences the thoughts, attitudes, and behaviour of others. According to John Newstrom and Keith Davis leadership is the process of influencing and supporting others to work enthusiastically towards achieving objectives. It is a process whereby one individual influences other group members toward the attainment of defined group or organizational goals. Leaders set a direction for the rest of the people; they help others see what lies ahead; visualize what to achieve; encourage and inspire others. Leadership is the ability to get other people to do something significant and energize people towards a goal. It influences a group of individuals to achieve a common goal. It contributes for the success of an individual, group or organization. It transforms policies into action.It utilizes the potential in an organization and its people. So we can see that leadership is a major way in which people change. ",
  '11': 'Thar Desert is situated on the border of India and Pakistan. A large part of it is in Marwar region of Rajasthan state. This place receives very little rain and there are no large rivers flowing. As a result very few trees grow here and very few crops can be grown. Only grass grows here. People here mainly depend upon grazing sheep, goats and camels. They take great care to store rain water for drinking for the animals and human beings and also for some agriculture. The shepherds usually travel across many states with their herds and usually come back before the rainy season to Thar. They make a living by selling goats and wool of the sheep. Many traders coming from Iran and Afghanistan or going to those countries pass through this desert. They stop over at convenient places to rest. Slowly these places grew into important towns and cities like Jaisalmer, Bikaner, Jodhpur. Many pilgrims going to Dwarka in Gujarat or to Mecca and Madina in Arabia or to Ajmer and Pushkar lake would pass through this area along with the traders. Thus over centuries people of many religions like Bohra Muslims, Sunni Muslims, Shia Muslims, Jains, Shaivas, Vaishnavas and Sikhs settled down in these towns and cities. Similarly, many Marwari traders from these parts went all over India and settled in several places. Some fifty years ago a large canal was built from the Punjab rivers to bring water to the Northern part of Thar desert. Along the canals came up new and prosperous villages many people from Punjab and Haryana came and settled down in these new villages. Earlier people mainly ate rotis made of bajra with green gram or black gram and ate of vegetables that grew on some trees (Sangri) and thorny bushes. These were dried and eaten throughout the year.',
  '12': "All changes in the weather are caused by the sun. The sun is a huge sphere of hot gases at a very high temperature. The distance of the sun from us is very large. Even then the energy sent out by the sun is so huge that it is the source of all heat and light on the earth. So, the sun is the primary source of energy that causes changes in the weather. Energy absorbed and reflected by the earth's surface, oceans and the atmosphere play important roles in determining the weather at any place. If you live near the sea, you would have realised that the weather at your place is different from that of a place in a desert, or near a mountain. The people living in the coastal areas experience an interesting phenomenon. During the day, the land gets heated faster than the water. The air over the land becomes hotter and rises up. The cooler air from the sea rushes in towards the land to take its place. The warm air from the land moves towards the sea to complete the cycle. The air from the sea is called the sea breeze. To receive the cooler sea breeze, the windows of the houses in coastal areas are made to face the sea. At night it is exactly the reverse. The water cools down more slowly than the land. So, the cool air from the land moves towards the sea. This is called the land breeze. When we come out in the sun, we feel warm. Heat cannot reach us by conduction or convection as there is no medium such as air in most part of the space between the earth and the sun. From the sun the heat comes to us by another process known as radiation. The transfer of heat by radiation does not require any medium. It can take place whether a medium is present or not. When we sit in front of a room heater, we get heat by this process. A hot utensil kept. ",
  '13': "'All changes in the weather are caused by the sun. The sun is a huge sphere of hot gases at a very high temperature. The distance of the sun from us is very large. Even then the energy sent out by the sun is so huge that it is the source of all heat and light on the earth. So, the sun is the primary source of energy that causes changes in the weather. Energy absorbed and reflected by the earth's surface, oceans and the atmosphere play important roles in determining the weather at any place. If you live near the sea, you would have realised that the weather at your place is different from that of a place in a desert, or near a mountain. The people living in the coastal areas experience an interesting phenomenon. During the day, the land gets heated faster than the water. The air over the land becomes hotter and rises up. The cooler air from the sea rushes in towards the land to take its place. The warm air from the land moves towards the sea to complete the cycle. The air from the sea is called the sea breeze. To receive the cooler sea breeze, the windows of the houses in coastal areas are made to face the sea. At night it is exactly the reverse. The water cools down more slowly than the land. So, the cool air from the land moves towards the sea. This is called the land breeze. When we come out in the sun, we feel warm. Heat cannot reach us by conduction or convection as there is no medium such as air in most part of the space between the earth and the sun. From the sun the heat comes to us by another process known as radiation. The transfer of heat by radiation does not require any medium. It can take place whether a medium is present or not. When we sit in front of a room heater, we get heat by this process. A hot utensil kept. '",
  '14': 'Nearly half of the premature death is a result of unhealthy lifestyles such as insufficient exercise, something poor diet, and drinking habits. These factors increase the risk of diabetes, high blood press sure, heart attack, and stroke. And we live in a country where cardiovascular disease is the leading cause of death. However, you can make a few changes in your lifestyles and soon you see the results. If you are a chain smoker, you need to quit as it is highly are a chain smoker, you need to quit as it is highly harmful to your health. Yes, it is not easy, but you can take help from the professionals and start with limiting yourself to one or two cigarettes a day. This will help you to quit smoking entirely. Make sure you maintain a healthy weight. You can do it by going for a run or walk, doing some exercise, hitting the weigh in the gym, swimming in the pool or rock climbing or weekends. It does not matter what you do, as long as you are physically active, it is good for your heart and body. You can go out to play football, volleyball, basketball or any game if you are not able to do all the other things. Drinking alcohol is not good for health, but there is a difference between an addict and a so-called drinker. Make sure you limit your alcohol to social gatherings only. Make sure you talk to your doctor if you are addicted to drinking. What you put inside your mouth directly affects your heart. Unhealthy food will increase your bad cholesterol level which is one of the main causes of heart attacks. It is recommended to eat a healthy diet that includes a variety of fruits and green veggies, and other highly nutritional food items You should drink more water and limit the usage of saturated fat, cholesterol, trans fat, red . ',
  '15': "'A democratic country needs effective leadership to lead its citizens to new heights and horizons. Effective leadership helps our nation during times of difficulties. It makes a business organization successful. It enables a nongovernmental organization to fulfil its mission. It fulfils the goal of social work. The effective leadership and guidance from parents enable children to develop their personality. The absence of leadership affects the functioning of any organisation. Without proper leadership, organizations move slowly, stagnate, and lose their way. The absence or failure of leadership may lead to ineffective decision making. A social worker can't perform effectively without leadership skills. Leadership is a process whereby an individual influences a group of individuals to achieve a common goal. It is a process by which a person influences the thoughts, attitudes, and behaviour of others. According to John Newstrom and Keith Davis leadership is the process of influencing and supporting others to work enthusiastically towards achieving objectives. It is a process whereby one individual influences other group members toward the attainment of defined group or organizational goals. Leaders set a direction for the rest of the people; they help others see what lies ahead; visualize what to achieve; encourage and inspire others. Leadership is the ability to get other people to do something significant and energize people towards a goal. It influences a group of individuals to achieve a common goal. It contributes for the success of an individual, group or organization. It transforms policies into action.It utilizes the potential in an organization and its people. So we can see that leadership is a major way in which people change the minds of others and move organizations forward to accomplish identified goals. A leader can be defined as a person who is able to get others to follow willingly. Leader is a person committed to the organization and the people who work together to accomplish the organization's vision and mission.'"
  };

document.getElementById('text-selector').addEventListener('change', function() {
  var selectedTextKey = this.value;
  if (selectedTextKey in providedTexts) {
    document.getElementById('text1').value = providedTexts[selectedTextKey];
  } else {
    document.getElementById('text1').value = ''; 
  }
});
